default: &default
  adapter: postgresql
  encoding: utf8
  pool: 10
  timeout: 5000
  username: postgres
  password:

development:
  <<: *default
  database: test_solver_development

test:
  <<: *default
  database: test_solver_test

production:
  <<: *default
  database: test_solver_production
  username: test_solver
  password: <%= ENV['TEST_SOLVER_DATABASE_PASSWORD'] %>
